#!/bin/sh
CurDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$CurDir"

# Stores some self-calibration log/data
if [ ! -d ./flash_txt ]; then
  mkdir flash_txt
fi

# Is libUSB library available?
if [ ! -f /opt/local/lib/libusb-legacy/libusbpp-legacy-0.1.4.dylib ]; then
	# Create folder trail. Try not to step on existing folders toes!
	if [ ! -d /opt/local/lib/ ]; then
		if [ ! -d /opt/local/lib/ ]; then
			if [ ! -d /opt/local/ ]; then
				if [ ! -d /opt/ ]; then
					sudo mkdir /opt/
				fi
				sudo mkdir /opt/local/
			fi
			sudo mkdir /opt/local/lib/
		fi
	fi
  sudo ln -s "$CurDir/libusb-legacy/" /opt/local/lib/
fi

# Start OWON Software!
java -jar ./plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar

### TEST ###
### Remove flashmemory.txt to prevent 'Hardware changed' errors ###
rm ./flash_txt/flashmemory.txt